sudo: false
language: node_js
node_js:
  - "0.12"

addons:
  code_climate:
    repo_token: $CC_REPO_TOKEN

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"
  - "npm config set spin false"

script: npm run test-ci
install:
  - node --version
  - npm --version
  - git --version
  - npm install


after_script:
  - codeclimate-test-reporter < /coverage/PhantomJS%201.9.8%20%28Mac%20OS%20X%200.0.0%29/lcov.info